before:
  hooks:
    - go mod download
builds:
- main: ./cmd/ramdisk/ramdisk.go
  env:
  - CGO_ENABLED=0
  goos:
    - linux
    - darwin
  ignore:
    - goos: darwin
      goarch: 386
archive:
  replacements:
    darwin: macOS
    386: i386
    amd64: x64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
brew:
  name: ramdisk
  description: Convenience wrapper for creating RAM disks.
  homepage: https://github.com/mroth/ramdisk
  github:
    owner: mroth
    name: homebrew-formulas
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^trivial:'
    - '^release:'
