language: go
go:
  - "1.11.x"

matrix:
  include:
    # utilize xcode builds to test different macOS versions,
    # see: https://docs.travis-ci.com/user/reference/osx/#macos-version
    - name: macOS 10.13
      osx_image: xcode9.4 # => macOS 10.13
      os: osx
    - name: macOS 10.12
      osx_image: xcode9.2 # => macOS 10.12
      os: osx
    - name: macOS 10.11
      osx_image: xcode8   # => macOS 10.11
      os: osx
    # osx_image: xcode6.4 # => macOS 10.10 deprecated on travis-ci Jan2019
    # linux requires sudo to run our integration tests
    - name: Linux
      os: linux
      sudo: required
      env: SUDO_REQUIRED=true

script:
  - |
    if [ "${SUDO_REQUIRED}" == "true" ]; then
      sudo env "PATH=$PATH" go test -v
    else
      go test -v
    fi
